### ISSUE TITLE
Failed to init on MySQL 5.5

### ISSUE THREAD

**Issue by demamoh** [cayleygraph/cayley#753]
**Description**

Setting up cayley to use on an existing mysql 5.5 db fails trying to init. 

**Steps to reproduce the issue:**
1. Use mysql 5.5
2. Use this config file
```

store:
  # backend to use
  backend: mysql
  # address or path for the database
  address: "address"
  # open database in read-only mode
  read_only: false
  # backend-specific options
  options:
    nosync: false
query:
  timeout: 10s
load:
  ignore_duplicates: false
  ignore_missing: false
  batch: 10000
```
3. Run this docker command 
`docker run --name cayley -v data:/data -p 64210:64210 -d quay.io/cayleygraph/cayley --init -c /data/cayley.yml`
**Received results:**

```
1 quadstore.go:222] Cannot create nodes table: Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(6)
```

**Expected results:**

**Output of `cayley version` or commit hash:**

```
Be able to query existing db using cayley
```

**Environment details:**

Backend database: `mysql 5.5`
