### ISSUE TITLE
 Kelly Card died

### ISSUE THREAD

**Issue by xingxing9688** [cayleygraph/cayley#783]
```
store:
  backend: mongo
  # address or path for the database
  address: "user:passwd@127.0.0.1:27017"
  # open database in read-only mode
  read_only: false
  # backend-specific options
  options:
    database_name: cayley
query:
  timeout: 30s
load:
  ignore_duplicates: false
  ignore_missing: false
  batch: 100000
```

cayley version: 0.75  

After the data is imported for a while or the piece is gone, the process is gone and the program is dead.
