### ISSUE TITLE
how can I run cayley in docker 

### ISSUE THREAD

**Issue by wurangbo** [cayleygraph/cayley#894]
I want to run cayley in docker and configure as below:  
```yaml
cayley:
    container_name: phoenix-cayley
    image: cayleygraph/cayley
    ports:
      - "64210:64210"
    environment:
      TZ: "Asia/Shanghai"
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
```
but get error:
`Error: open data/cayley.db/indexes.bolt: no such file or directory`

**Comment by iddan** [comment]
Hello, it seems like you need to init the database.
To do that:
```yaml
cayley:
    container_name: phoenix-cayley
    image: cayleygraph/cayley
    cmd: --init
    ports:
      - "64210:64210"
    environment:
      TZ: "Asia/Shanghai"
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
```
